export type ValidationStatus =
  | "MET"
  | "NOT_MET"
  | "PARTIALLY_MET"
  | "AMBIGUOUS";

export interface ValidationResult {
  requirementId: string;
  status: ValidationStatus;

  // Evidence found in the proposal
  evidence?: {
    text: string;
    pageNumber: number;
    fileUrl?: string;
  };

  // Explanation of why the requirement is met or not (generated by AI)
  reasoning: string;

  // Confidence score of the validation
  confidence: number; // 0.0 to 1.0

  // Manual override by the human reviewer
  manualOverride?: {
    isOverride: boolean;
    newStatus: ValidationStatus;
    comment: string;
    updatedAt: Date;
  };
}
